### ISSUE TITLE
when I use this Plugin,I have some problem

### ISSUE THREAD

**Issue by wghust** [soton-ecs-2014-gdp-12/videogular-questions-example#21]
I use this in other project. and get out this error

```
GET http://localhost:9000/undefined 404 (Not Found)
```

I find this error is because I can't get  $scope.questions . What can I do?

**Comment by chewett** [comment]
Unless you can provide more information than that we wont be able to help you.

Its visiting /undefined since you $scope.questions is out of your scope. Try using the angular plugin batarang to help debug your scope issues.

**Comment by wghust** [comment]
I print out the $scope, It has the prototype "questions". But when I print out the "$scope.questions", It will be undefined, So I make 500ms to run the function of `webWorker.init()`, the error will disappear, but it don't work, no popup, no effect. can you help me, how can I use this plugin in other project?

**Comment by wghust** [comment]
@chewett

**Comment by chewett** [comment]
Does the example shown here work? Have you actually loaded the questions into your project? You need to actually provide a quiz definition file and it to be valid otherwise it wont load questions and it will be undefined.

**Comment by wghust** [comment]
I have loaded the questions plugin. and I use this in this way.

``` javascript
<vg-questions vg-questions-data="config.plugins.questions.data.url">
        </vg-questions>
```

and add the module name `uk.ac.soton.ecs.videogular.plugins.questions`

than config the video by this way:

``` javascript
$scope.config = {
                            autoHide: true,
                            autoPlay: false,
                            loop: false,
                            preload: "auto",
                            transclude: true,
                            sources: $scope.videos[0].sources,
                            plugins: {
                                cuepoints: {
                                    theme: {
                                        url: "bower_components/videogular-cuepoints/cuepoints.css"
                                    }
                                },
                                questions: {
                                    data: {
                                        url: "scripts/controllers/simple_questions.js"
                                    }
                                }
                            }
                            //theme: ENV.name==='development'?'bower_components/videogular-themes-default/videogular.css':'styles/vendor.css'
                        };
```

Have I  lost something  in this process?

**Comment by wghust** [comment]
@chewett   Thanks

**Comment by chewett** [comment]
Its very hard to tell from the limited information here. Unless you can provide a fully set up website I can look into, its hard to tell since there doesnt seem to be any errors from our end.

It looks like your questions are never loaded, or fail to load. If you are working on this I suggest you start from the website example and adapt it.

**Comment by wghust** [comment]
@chewett Can I email you about this questions?

**Comment by wghust** [comment]
@chewett I have Imported this plugin, but no popup after I client the button of 'preview', I really have set one question before, But no popup, is this the problem of the path of template?

**Comment by chewett** [comment]
As I have said above it is hard to tell what you have done wrong without looking into it. I will not be able to provide support unless you can specifically show me an instance of it not working where I can test it myself, and then I only have time to have a cursory glance over it.

We will look into fixing any bugs with the plugin but are not able to support implementing the plugin. This repository is merely an example of what you can do.
